apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
    managed-by: helm
data:
  config.yaml: |
    model_list:
    {{- toYaml .Values.modelList | nindent 4 }}

    litellm_settings:
      callbacks: ["prometheus"]

    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY

    router_settings:
      num_retries: 2
      allowed_fails: 3
      cooldown_time: 30
