apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
    managed-by: helm
type: Opaque
stringData:
  api-key: {{ .Values.apiKeys.openaiApiKey | quote }}
