apiVersion: v1
kind: Secret
metadata:
  name: ai-models-api-keys
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Chart.Name }}
    managed-by: helm
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.apiKeys.mistralApiKey | quote }}
  ANTHROPIC_API_KEY: {{ .Values.apiKeys.anthropicApiKey | quote }}
