apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.serviceAccount.name }}
  namespace: {{ .Values.deployment.serviceAccount.namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.deployment.serviceAccount.name }}-token
  namespace: {{ .Values.deployment.serviceAccount.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.deployment.serviceAccount.name }}
type: kubernetes.io/service-account-token
