apiVersion: v2
name: home-sweet-cloud-infrastructure
description: Base infrastructure for home-sweet-cloud Kubernetes cluster
type: application
version: 0.2.0
appVersion: "1.0"
keywords:
  - infrastructure
  - cert-manager
  - rbac
maintainers:
  - name: Lukas Wöllhaf
    email: infra@lukaswoellhaf.com
